version: "3.8"
name: "pbtech"
volumes:
  mongodb-data:
   name: mongodb-data
  mongod-config:
   name: mongod-config
  mongodb-logs:
   name: mongodb-logs

    
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - mongodb-data:/data/db
      - mongod-config:/conf
      - mongodb-logs:/logs
    expose:
      - '27017'
    ports:
      - '27017:27017'
    networks:
      - pbtech
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    
    
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    expose:
    - '8081'
    ports:
    - '8081:8081'
    networks: 
    - pbtech
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://admin:admin123@0.0.0.0:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  pbtech: